# Generated by Django 2.0.2 on 2018-02-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyScoreForUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Предмет ЕГЭ',
                'verbose_name_plural': 'Предметы ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=200)),
                ('full_title', models.TextField()),
                ('specialties', models.ManyToManyField(through='universities.SpecialtyScoreForUniversity', to='universities.Specialty')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.AddField(
            model_name='specialtyscoreforuniversity',
            name='subjects',
            field=models.ManyToManyField(to='universities.Subject'),
        ),
        migrations.AddField(
            model_name='specialtyscoreforuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
